const CHARACTER_IMAGE_HEIGHT = 48;
const CHARACTER_IMAGE_WIDTH = 24;

export const EXHIBITION_2D_MOVING_DISTANCE_PER_STEP = 4;
export const EXHIBITION_2D_HEIGHT = 300;
export const EXHIBITION_2D_WIDTH = 400;

// Character

export const EXHIBITION_2D_CHARACTER_ANIMATION_FRAME_COUNT = 4;
export const EXHIBITION_2D_CHARACTER_ANIMATION_PER_FRAME = 4;
export const EXHIBITION_2D_CHARACTER_DEFAULT_DIRECTION = "right";
export const EXHIBITION_2D_CHARACTER_HEIGHT = 128;
export const EXHIBITION_2D_CHARACTER_WIDTH = Math.floor(
  (EXHIBITION_2D_CHARACTER_HEIGHT / CHARACTER_IMAGE_HEIGHT) *
    CHARACTER_IMAGE_WIDTH
);

export const EXHIBITION_2D_CHARACTER_X = Math.floor(
  (EXHIBITION_2D_WIDTH - EXHIBITION_2D_CHARACTER_WIDTH) / 2
);
export const EXHIBITION_2D_CHARACTER_Y =
  EXHIBITION_2D_HEIGHT - EXHIBITION_2D_CHARACTER_HEIGHT - 37;

export const EXHIBITION_2D_CHARACTER_HORIZONTAL_OFFSET_STEP = Math.floor(
  EXHIBITION_2D_CHARACTER_X / EXHIBITION_2D_MOVING_DISTANCE_PER_STEP
);

// Background

// (背景に使用する最大の画像サイズ - 画面サイズ) / Step 毎の横幅 + キャラクターが画面中央に移動するまで固定するため、その移動分の Step 数
export const EXHIBITION_2D_BACKGROUND_MAX_STEP = Math.floor(
  (1947 - EXHIBITION_2D_WIDTH) / EXHIBITION_2D_MOVING_DISTANCE_PER_STEP +
    EXHIBITION_2D_CHARACTER_HORIZONTAL_OFFSET_STEP
);

// (背景に使用する最大の画像サイズ - キャラクターの横幅) / Step 毎の横幅
export const EXHIBITION_2D_CHARACTER_MAX_STEP = Math.floor(
  (1947 - EXHIBITION_2D_CHARACTER_WIDTH) /
    EXHIBITION_2D_MOVING_DISTANCE_PER_STEP
);
