name: Build And Lint

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    strategy:
      matrix:
        node-version: [14.15.0]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          path: "**/node_modules"
      - run: yarn
      - run: yarn run next build

  lint:
    strategy:
      matrix:
        node-version: [14.15.0]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          path: "**/node_modules"
      - run: yarn
      - run: yarn run eslint --ext .js,.ts,.tsx --ignore-path .gitignore .
      - run: yarn run stylelint --ignore-path .gitignore **/*.scss
