name: Contentful

on: [workflow_dispatch]

jobs:
  update:
    env:
      CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_CONTENT_DELIVERY_API_ACCESS_TOKEN }}
      CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          node scripts/contentful.js
      - run: |
          git config user.name "ameri-shirosaki"
          git config user.email "59396199+ameri-shirosaki@users.noreply.github.com"
          git add public
          git commit -m "Update public/contents"
          git push origin master

    strategy:
      matrix:
        node-version: [14.15.0]
        os: [ubuntu-latest]
