name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    env:
      TZ: Asia/Tokyo
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    strategy:
      matrix:
        node-version: [14.15.0]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # https://github.com/actions/create-release/pull/11#issue-330958665
      - id: tag_name
        run: echo "::set-output name=body::$(date '+%Y%m%d-%H%M')"
      - run: yarn
      - id: deployment
        uses: chrnorm/deployment-action@releases/v1
        with:
          environment: Production
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn run vercel -b GITHUB_RELEASE_TAG_NAME=${{ steps.tag_name.outputs.body }} -b GITHUB_REPOSITORY=$GITHUB_REPOSITORY -b GITHUB_SHA=$GITHUB_SHA --prod -t $VERCEL_TOKEN
      - if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.body }}
