name: Deploy to Preview

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    strategy:
      matrix:
        node-version: [14.15.0]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - id: deployment
        uses: chrnorm/deployment-action@releases/v1
        with:
          environment: Preview
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn run vercel -b GITHUB_REPOSITORY=$GITHUB_REPOSITORY -b GITHUB_SHA=$GITHUB_SHA -t $VERCEL_TOKEN
      - if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
